### ISSUE TITLE
Temperature sensor

### ISSUE THREAD

**Issue by marmotae** [lewisxhe/esp32-camera-bme280#6]
Hello while using your code I have found that temperature readings seem too high on the bme280, is there a correct calibration for it?

**Comment by lewisxhe** [comment]
@marmotae The main high temperature is mainly because the temperature of the main board is high, so the temperature detection of 280 is not in accordance with the actual use environment. I used to use the esp32 on-chip temperature sensor for temperature calibration, but the esp32 on-chip temperature sensor seems to be no longer usable, so there is no way.
